### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [RigelWalshe/dvp-u6-netflix-data#1]
Pandas and CSV (4/4)
The Jupyter notebook imports the necessary libraries and converts the CSV to a Pandas DataFrame. 

Implementation of visualizations (4/4)
The Jupyter notebook renders all Seaborn and Matplotlib visualizations and content provided in the design specification.

Color (4/4)
Color carries meaning and visualizations use different palettes with purpose.

Style (4/4)
The chart labels and titles are concise, easy to read, and some titles are framed as questions.

Presentation and framing of visualizations (4/4)
Presentation cohesively presents every chart and has an appropriate description for each, with further research outlined in the notes.

Overall, great job! Your powerpoint was excellent. :)

**Comment by RigelWalshe** [comment]
Thanks alot!
